### ISSUE TITLE
Working example!

### ISSUE THREAD

**Issue by raffdoc** [lmmx/gdocs2Rmd#1]
I think this is very good idea.
Could you give some working example of this script. 
Many thanks.

**Comment by lmmx** [comment]
It's still under development and still only outputting markdown (md not Rmd):

* open a Google Doc
* go to `Tools > Script Editor > Create script for blank project`
* Click on the Code.gs file
* Paste in [the contents of the working script](https://raw.githubusercontent.com/lmmx/gdocs2Rmd/master/converttomarkdown.gapps)
* Select `setupScript` from the dropdown meny and run it
    * Repeat for `convertSingleDoc`
    * To run this for every Google Doc in a folder choose `convertFolder`

If you've not already run this script before for a file in the given folder it'll create a sub-directory named "Markdown", in which the file will go in your Drive.

All the further work will be in getting Rmarkdown-specific features like code chunks. Leave another comment if you want me to add any more detail here and thanks for your interest, feel free to propose any changes to the script :smile:
